[package]
edition = "2021"
name    = "better-os"
version = "0.1.0"

[[bin]]
name = "better-os"
path = "src/main.rs"
test = false



[dependencies]
# try 0.7.0 if u want
embassy-executor    = { version = "0.7.0", features = [ "defmt", "task-arena-size-98304"] }
esp-hal = { version = "1.0.0-rc.0", features = [ "unstable", "esp32c6", "rt", "defmt" ] }
esp-hal-embassy = { version = "0.9.0",  features = ["esp32c6"]  }
esp-alloc = { version = "0.8.0" }
esp-radio = { version = "0.15.0", features = [ "unstable", "ble", "esp32c6" ] }
esp-radio-preempt-baremetal = { version = "0.0.1", features = ["defmt", "esp32c6"] }
trouble-host = { git = "https://github.com/embassy-rs/trouble", rev = "b57bb1c32fa16d1f81a2b0123ec723c9da7defb4", features = ["default-packet-pool-mtu-255"] }
static_cell = "2"
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32c6"] }


# from top

bt-hci = { version = "0.4" }


# unchecked needs replacement



heapless = { version = "0.8", features = ["defmt-03"] }

embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
defmt = "1.0.1"


panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
rtt-target = { version = "0.6.1", features = ["defmt"] }

nb = "1.1.0"


embassy-time = { version = "0.4.0", features = ["generic-queue-8", "defmt"] }



embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }

micromath = "2.1.0"
fixed = "1.28.0"

embassy-futures = "0.1.1"
embassy-sync = { version = "0.7.0" }
log = "0.4.27"
async-trait = "0.1.88"

font8x8 = { version = "0.3", default-features = false, features = ["unicode"] }

tinybmp = { version = "0.6.0", features = [] }
libm = "0.2.15"





[features]
default = ["single_thread_static_parser"]
single_thread_static_parser = []






[patch.crates-io]
esp-radio = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}
esp-radio-preempt-baremetal = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}
esp-backtrace = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}
esp-hal = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}
esp-bootloader-esp-idf = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}
esp-hal-embassy = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}
esp-alloc = {git = "https://github.com/esp-rs/esp-hal.git", rev = "a7bd8980ea2aff28d20bc501e86886dc917c9e28"}


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false


