pub(super) use super::FontId;
pub(super) use super::{Font, FontKerning, Glyph, GlyphMap};

pub mod montserrat_10;
pub mod montserrat_12;
pub mod montserrat_14;
pub mod montserrat_16;
pub mod montserrat_18;
pub mod montserrat_20;
pub mod montserrat_22;
pub mod montserrat_24;
pub mod montserrat_26;
pub mod montserrat_28;
pub mod montserrat_30;
pub mod montserrat_32;
pub mod montserrat_34;
pub mod montserrat_36;
pub mod montserrat_38;
pub mod montserrat_40;
pub mod montserrat_42;
pub mod montserrat_44;
pub mod montserrat_46;
pub mod montserrat_48;
pub mod montserrat_8;
