/// Blending modes and blend descriptors for format-agnostic rendering
/// Based on LVGL v9.x blend architecture

/// Blend mode for compositing operations
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlendMode {
    /// Standard alpha blending (Porter-Duff Source Over)
    Normal,
    /// Add color channels
    Additive,
    /// Subtract foreground from background
    Subtractive,
    /// Multiply colors
    Multiply,
    /// Absolute difference
    Difference,
}

/// Source data for blending
#[derive(Debug, Clone)]
pub enum BlendSource {
    /// Solid color fill
    SolidColor {
        color: super::color::ColorAlpha,
    },
    /// Horizontal color span (for gradients)
    HorizontalSpan {
        colors: alloc::vec::Vec<super::color::ColorAlpha>,
    },
    /// Image data
    Image {
        buffer: alloc::vec::Vec<u8>,
        width: u32,
        height: u32,
        format: super::color::ColorFormat,
    },
}

/// Abstract blend descriptor - generated by primitives, executed by draw targets
/// This enables format-agnostic rendering following LVGL architecture
#[derive(Debug, Clone)]
pub struct BlendDescriptor {
    /// Type of blend operation
    pub mode: BlendMode,
    /// Source region (if applicable)
    pub source: Option<BlendSource>,
    /// Destination region
    pub dest_rect: super::geometry::Rect,
    /// Global opacity (0-255)
    pub opacity: super::color::Opacity,
    /// Optional per-pixel alpha mask
    pub mask: Option<alloc::vec::Vec<u8>>,
}

impl BlendDescriptor {
    /// Create a solid color fill blend
    pub fn solid_fill(
        rect: super::geometry::Rect,
        color: super::color::ColorAlpha,
        mode: BlendMode,
    ) -> Self {
        Self {
            mode,
            source: Some(BlendSource::SolidColor { color }),
            dest_rect: rect,
            opacity: super::color::Opacity::OPAQUE,
            mask: None,
        }
    }
    
    /// Create a solid color fill with opacity
    pub fn fill_with_opacity(
        rect: super::geometry::Rect,
        color: super::color::ColorAlpha,
        opacity: super::color::Opacity,
        mode: BlendMode,
    ) -> Self {
        Self {
            mode,
            source: Some(BlendSource::SolidColor { color }),
            dest_rect: rect,
            opacity,
            mask: None,
        }
    }

    /// Create a clear operation (no source)
    pub fn clear(rect: super::geometry::Rect) -> Self {
        Self {
            mode: BlendMode::Normal,
            source: None,
            dest_rect: rect,
            opacity: super::color::Opacity::OPAQUE,
            mask: None,
        }
    }
    
    /// Add a mask to this blend descriptor
    pub fn with_mask(mut self, mask: alloc::vec::Vec<u8>) -> Self {
        self.mask = Some(mask);
        self
    }
}

extern crate alloc;
